apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sandbox
  name: techtrends
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - name: techtrends
        image: rodrigothd/techtrends:latest                
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3111
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 5
          periodSeconds: 5
